name             'apache2-magentodevsite'
maintainer       'Stephen Lang'
maintainer_email 'info@skl.me'
license          'All rights reserved'
description      'Configures magento.dev vhost'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apache2'
depends          'php'
depends          'mysql'
